const {randNumString} = require("../tools/tools.js")
let enemyInterface = {
    _id: `${randNumString()}`,
    maxDistance: 1.1,
    name: "dirtGoblin",
    dn: "dirt goblin",
    modelStyle: "goblin",
    stats: { 
        dmg: 10,
        magDmg: 1, 
        accuracy: 1, //10
        critical: 1.4, 
        spd: 3,
        atkSpd: 2100
    },
    deathSound: "goblinDeathS",
    lvl: 2,
    hp: 120,
    maxHp: 120,
    expToGain: 100,
    x:3.6,
    z: -40,
    origPos: {x:3.6,z: -40,},
    effects: [
        {name: 'spdrain', dn:'SP Drained', spcost: 20, hpcost:0, mpcost:0, hungercost:4, energycost: 0}
    ],
    effectsWhenHit: [
        {name: 'spdrain', dn:'SP Drained', spcost: 20, hpcost:0, mpcost:0, hungercost:4, energycost: 0}
    ],
    titles: ['human killer'],
    skills: [], 
    aptitude: ['light'],
    blessings: [],
    currentPlace: "wisemanVillage",
    status: [], // sickness //poisoned etc
    regens: {sp: 1, hp: 1, mana: 1},
    monsSoul: 2, // toReceive when killed
    race: "monster",
    characterType:"enemy",// npcStandby//npcEnemy//npcFighter//npcWalk
    actionType: "chasing", //idle//chasing//throwing//dynamic
    randomSpeech: [            
        {name: "", message: "Weapons are reliable when facing danger"}, 
        {name: "", message: "But If you're planning to flee, better drop it to loss weight"},
        {name: "", message: "We have Geralt for crafting weapons, he just need the materials for it"}
    ],
    _isMoving: false,
    _targetId: false,
    _dirTarg: {x:0,z:0},
    _attacking: false,
}
module.exports = [
    enemyInterface,
    // dummy on training hall
    {...enemyInterface,
        _id: `${randNumString()}`, 
        x: 0, 
        z: 5,
        origPos: {x: 0, z: 5},
        currentPlace: "churchTrainingHall",
        actionType: "idle",
        name: "wooddummy",
        dn: "Wood Dummy",
        modelStyle: "dummy",
        deathSound: "brokenWoodS",
        hp: 30,
        maxHp: 30,
        stats: { 
            dmg: 1,
            magDmg: 1, 
            accuracy: 1, //10
            critical: 1.4, 
            spd: 3,
            atkSpd: 3000
        },
    },
    {...enemyInterface,
        _id: `${randNumString()}`, 
        x: -3, 
        z: 5,
        origPos: {x: -3, z: 5},
        currentPlace: "churchTrainingHall",
        actionType: "idle",
        name: "wooddummy",
        dn: "Wood Dummy",
        modelStyle: "dummy",
        deathSound: "brokenWoodS",
        hp: 30,
        maxHp: 30,
        stats: { 
            dmg: 1,
            magDmg: 1, 
            accuracy: 1, //10
            critical: 1.4, 
            spd: 3,
            atkSpd: 3000
        },
    },
    {...enemyInterface,
        _id: `${randNumString()}`, 
        x: 1, 
        z: 5,
        origPos: {x: 1, z: 5},
        currentPlace: "churchTrainingHall",
        actionType: "idle",
        name: "wooddummy",
        dn: "Wood Dummy",
        modelStyle: "dummy",
        deathSound: "brokenWoodS",
        hp: 30,
        maxHp: 30,
        stats: { 
            dmg: 1,
            magDmg: 1, 
            accuracy: 1, //10
            critical: 1.4, 
            spd: 3,
            atkSpd: 3000
        },
    },
    // {...enemyInterface,
    //     _id: `${randNumString()}`, 
    //     x: 2, 
    //     z: -4,
    //     origPos: {x: 2, z: -4},
    //     currentPlace: "churchTrainingHall",
    //     actionType: "idle",
    //     hp: 20000,
    //     maxHp: 20000, 
    //     stats: { 
    //         dmg: 1,
    //         magDmg: 1, 
    //         accuracy: 1, //10
    //         critical: 1.4, 
    //         spd: 3,
    //         atkSpd: 3000
    //     },
    // },
    {...enemyInterface,
        _id: `${randNumString()}`, 
        x: -15, 
        z: -15,
        origPos: {x: -15, z: -15}
    },
    {...enemyInterface,
        _id: `${randNumString()}`, 
        x: -30, 
        z: -30,
        origPos: {x: -30, z: -30},
        currentPlace: "afterWarScene",
    },
    {...enemyInterface,
        _id: `${randNumString()}`, 
        x: 1, 
        z: 55,
        origPos: {x: 1, z: 55},
        currentPlace: "afterWarScene",
    },
    {...enemyInterface,
        _id: `${randNumString()}`, 
        x: 10, 
        z: 40,
        origPos: {x: 10, z: 40},
        currentPlace: "afterWarScene",
    },
]